#!/usr/bin/env bash
# script to install and setup
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw m'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
# test nginx
sudo nginx -t
sudo service nginx reload
