#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://https://www.youtube.com/watch?v=QpIHg8dhBEE permanent;" /etc/nginx/sites-enabled/default

sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/page_error_404.html

sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default

sudo service nginx restart
